### ISSUE TITLE
Istio pod exclusion policy not kicking in when upstream host returns 5xx errors

### ISSUE THREAD

**Issue by balamuru** [istio/api#1068]
Steps to reproduce:
* Deploy httpbin in cluster , with the intent to echo back errors to user via /status/5xx endpoint
```
sh-4.2$ kubectl get svc httpbin -o yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"httpbin","namespace":"default"},"spec":{"clusterIP":"10.96.0.42","ports":[{"name":"http-httpbin-80","port":80,"protocol":"TCP","targetPort":80}],"selector":{"run":"httpbin"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2019-09-03T17:29:42Z"
  name: httpbin
  namespace: default
  resourceVersion: "534837"
  selfLink: /api/v1/namespaces/default/services/httpbin
  uid: add7f01d-9f9f-482b-ab61-c04ce789547a
spec:
  clusterIP: 10.96.0.42
  ports:
  - name: http-httpbin-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: httpbin
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
sh-4.2$ 

```

* Create virtual service for the httpbin deployment
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "httpbin-virtual-service"
spec:
  hosts:
  - "*"
  gateways:
  - my-istio-gateway
  http:
  - match:
    - uri:
        prefix: /status
    route:
    - destination:
        host: "httpbin"
        port:
          number: 80

```
* Create Destination Rule with consecutive errors set to 1 in order to trigger host exclusion on the second error response from httpbin
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: httpbin-dest-rule
spec:
  host: httpbin
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1000
      http:
        http1MaxPendingRequests: 1000
        maxRequestsPerConnection: 1000
    outlierDetection:
      consecutiveErrors: 1
      interval: 10s
      baseEjectionTime: 2m
      maxEjectionPercent: 100
      minHealthPercent: 0

```
 * Invoke a series of http status echo requests to the httpbin svc. Regardless of what is sent (503,504,505,404),  the responses are echoed back ((503,504,505,404)).  I would expect 5xx errors to be intercepted, pods excluded  and 503 to be returned back. Please clarify

```
$ siege --reps=1   http://127.0.0.1:31380/status/504
** SIEGE 4.0.4
** Preparing 25 concurrent users for battle.
The server is now under siege...
HTTP/1.1 504     0.01 secs:       0 bytes ==> GET  /status/504 ====> 1st error, 504 is returned 
HTTP/1.1 504     0.01 secs:       0 bytes ==> GET  /status/504 ====> 2nd error, 504 still returned 
HTTP/1.1 504     0.01 secs:       0 bytes ==> GET  /status/504
HTTP/1.1 504     0.01 secs:       0 bytes ==> GET  /status/504
HTTP/1.1 504     0.01 secs:       0 bytes ==> GET  /status/504
HTTP/1.1 504     0.01 secs:       0 bytes ==> GET  /status/504
HTTP/1.1 504     0.01 secs:       0 bytes ==> GET  /status/504
HTTP/1.1 504     0.00 secs:       0 bytes ==> GET  /status/504
HTTP/1.1 504     0.01 secs:       0 bytes ==> GET  /status/504
HTTP/1.1 504     0.00 secs:       0 bytes ==> GET  /status/504
HTTP/1.1 504     0.02 secs:       0 bytes ==> GET  /status/504
HTTP/1.1 504     0.01 secs:       0 bytes ==> GET  /status/504
HTTP/1.1 504     0.02 secs:       0 bytes ==> GET  /status/504
HTTP/1.1 504     0.02 secs:       0 bytes ==> GET  /status/504
HTTP/1.1 504     0.01 secs:       0 bytes ==> GET  /status/504
HTTP/1.1 504     0.02 secs:       0 bytes ==> GET  /status/504
HTTP/1.1 504     0.02 secs:       0 bytes ==> GET  /status/504
HTTP/1.1 504     0.01 secs:       0 bytes ==> GET  /status/504
HTTP/1.1 504     0.01 secs:       0 bytes ==> GET  /status/504
HTTP/1.1 504     0.01 secs:       0 bytes ==> GET  /status/504
HTTP/1.1 504     0.01 secs:       0 bytes ==> GET  /status/504
HTTP/1.1 504     0.01 secs:       0 bytes ==> GET  /status/504
HTTP/1.1 504     0.01 secs:       0 bytes ==> GET  /status/504
HTTP/1.1 504     0.01 secs:       0 bytes ==> GET  /status/504
HTTP/1.1 504     0.01 secs:       0 bytes ==> GET  /status/504

Transactions:		           0 hits
Availability:		        0.00 %
Elapsed time:		        0.03 secs
Data transferred:	        0.00 MB
Response time:		        0.00 secs
Transaction rate:	        0.00 trans/sec
Throughput:		        0.00 MB/sec
Concurrency:		        9.33
Successful transactions:           0
Failed transactions:	          25
Longest transaction:	        0.02
Shortest transaction:	        0.00
 
$ 
```

```
$ istioctl version --remote
client version: 1.2.2
citadel version: 1.2.2
egressgateway version: 1.2.2
galley version: 1.2.2
ingressgateway version: 1.2.2
pilot version: 1.2.2
policy version: 1.2.2
sidecar-injector version: 1.2.2
telemetry version: 1.2.2

```

It looks like this was an issue a while back. I'm running istion 1.2.2 . For my test, I tried between 1 - 4 replicas  of the svc with the same results
See
* https://stackoverflow.com/questions/55707778/istio-circuit-breaker-not-opening-the-circuit-on-consecutiveerrors-when-downstre
* https://github.com/istio/istio/issues/13682

**Comment by balamuru** [comment]
Verified on a different cluster with istio 1.2.5
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: httpbin-dest-rule
spec:
  host: httpbin
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 10
      http:
        http1MaxPendingRequests: 10000
        maxRequestsPerConnection: 10000
    outlierDetection:
      consecutiveErrors: 2
      interval: 10s
      baseEjectionTime: 2m
      maxEjectionPercent: 100
      minHealthPercent: 0

```

```
$ istioctl version
client version: 1.2.5
citadel version: 1.2.5
egressgateway version: 1.2.5
galley version: 1.2.5
ingressgateway version: 1.2.5
pilot version: 1.2.5
policy version: 1.2.5
sidecar-injector version: 1.2.5
telemetry version: 1.2.5
$ siege --reps=1 http://127.0.0.1:31380/status/504
** SIEGE 3.1.4
** Preparing 15 concurrent users for battle.
The server is now under siege...
HTTP/1.1 504   1.01 secs:       0 bytes ==> GET  /status/504
HTTP/1.1 504   1.01 secs:       0 bytes ==> GET  /status/504
HTTP/1.1 504   1.01 secs:       0 bytes ==> GET  /status/504
HTTP/1.1 504   1.01 secs:       0 bytes ==> GET  /status/504
HTTP/1.1 504   1.00 secs:       0 bytes ==> GET  /status/504
HTTP/1.1 504   1.01 secs:       0 bytes ==> GET  /status/504

```
