### ISSUE TITLE
Impact of namespace on RBAC objects is unclear

### ISSUE THREAD

**Issue by Phazyck** [istio/api#1294]
**Describe the feature request**

The documentation on [RBAC](https://istio.io/docs/reference/config/security/istio.rbac.v1alpha1/) should be extended, to explain the impact of the namespace used on `ServiceRole` and `ServiceRoleBinding` objects. It took me quite a while to realize that these objects should be placed in the same namespace as the services I'm trying to access.

Also, it is unclear whether it is possible to create an RBAC rule that targets multiple, or all namespaces.

**Describe alternatives you've considered**

None.

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Additional context**

Here's a concrete example of what I've been working on:

I have services in namespace `foo` which should be scraped by Prometheus, which is running in a different namespace, `telemetry`. Initially, I'd set up the RBAC objects in the `telemetry` namespace, but that didn't work. Finally, I ended up with the following, which seems to work:

```yaml
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: metrics-scraper
  namespace: foo
spec:
  rules:
  - services: [ "*" ]
    methods: [ "GET" ]
    paths: [ "/metrics" ]
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  annotations:
  name: prometheus-scrape-metrics
  namespace: foo
spec:
  subjects:
  - user: '*'
  roleRef:
    kind: ServiceRole
    name: metrics-scraper
```

The documentation didn't really make it clear that the namespace had to be the same as the application I'm trying to access - I had to figure that out myself through experimentation.

Additionally, it's not clear if there's a way to make a more general rule that will apply to all namespaces, or if I have to create rules for all other namespaces I also want to scrape.
