### ISSUE TITLE
Annotations code generator produces invalid code

### ISSUE THREAD

**Issue by esnible** [istio/api#1360]
To reproduce, add

```
  - name: istio.io/rev
    description: The Istio control plane revision associated with the resource
    deprecated: false
    hidden: false
    resources:
      - Service
      - Pod
```

to _istio.io/api/annotation/annotations.yaml_ and do `make`.

The produced output includes `Resources: []ResourceTypes{ ServicePod, },` which is invalid.  (It should be `Resources: []ResourceTypes{ Service, Pod, },`.
