### ISSUE TITLE
 wrong network example

### ISSUE THREAD

**Issue by magengbin** [istio/api#1461]
https://github.com/istio/api/blob/5f26aa5836791b1aeff8389aef6506352d469eb4/mesh/v1alpha1/network.proto#L105

Is there one more -, the correct one should be as follows:

```yaml
networks:
  network1:
    endpoints:
    - fromRegistry: registry1 #must match secret name in Kubernetes
    - fromCidr: 192.168.100.0/22 #a VM network for example
    gateways:
    - registryServiceName: istio-ingressgateway.istio-system.svc.cluster.local
      port: 15443
      locality: us-east-1a
    - address: 192.168.100.1
      port: 15443
      locality: us-east-1a
```
