### ISSUE TITLE
Clarity of destination policies

### ISSUE THREAD

**Issue by kyessenov** [istio/api#154]
As part of revamping Istio configuration in 0.2, we’re looking at expanding and clarifying the destination policy definition. The destination policy decides the load balancing strategy and circuit-breaking per groups of network endpoints, as selected by a service and a label selector.
For example, a policy:

```yaml
destination: reviews.default.svc.cluster.local
policy:
- labels:
    version: v1
  simple_cb:                                                                                                                                             
    max_connections: 100                                                                                                                                  
```
selects network endpoints of reviews labeled by version: v1 and applies a circuit breaker of max 100 connections to the group. The intention is that the route can refer to this group of endpoints and utilize the policy rule. However, there are several issues with this approach:
- Policies apply by the label selector chosen exactly by rules in the destination section. The route rule must explicitly refer to this version: v1 and not have any extra label selectors, such as env: prod.
- Policies are unique per each group of endpoints. The two policies for env: prod and version: v1, are not combined for env: prod, version: v1 policy. Moreover, if there is a need to apply special policy for certain sources (for example, an aggressive circuit breaker), then the current form does not permit specializing the rule by source or have two different policies for the same destination.

My personal proposal to deal with this problem, is to make the policy a general rule with match conditions for source and destination, with a special precedence field to disambiguate conflicts. Here is an example:

```yaml
kind: DestinationPolicy
name: my-policy
namespace: default:
precedence: 100 # highest wins
source:
  name: ratings
destination:
  name: reviews
  labels:
    version: v1
simple_cb:                                                                                                                                             
    max_connections: 100     
```

applies exclusively to ratings instances that refer to any reviews destination pods that match the label selector version: v1. That means if there is a route rule that has the following destination:

```yaml
destination:
  name: reviews
  labels:
    env: prod
    version: v1
```
then the destination of this rule inherits the CB policy above for all requests originating from ratings service. 

Thoughts? Ideas?
cc @rshriram @frankb

**Comment by frankbu** [comment]
Is still a DestinationPolicy kind resource? What would be the name and namespace? Is there a list of policies in the resource, or one per resource? Can you please flesh out the example a little more?

**Comment by rshriram** [comment]
From what I gathered,
```yaml
metadata:
  name: some-policy
  namespace: somenamespace
spec:
  source:
    name: ratings
    # optional namespace
  destination: 
    name: reviews
    #optional namespace
    labels:
      env: prod
      version: v1
  loadBalancing: 
    name: RANDOM
  precedence: 100 # highest wins
```

What I am unclear about is the semantics of source here. Am I expected to match this source exactly in my route rules? 
Also, will we be materializing each DP into its one cluster, even if its not referred to by any route?
And what happens if the route's tags don't match up? Will that end up creating yet another cluster?

**Comment by kyessenov** [comment]
There's ordering to label selectors which we would rely on to override policies. Envoy clusters are created implicitly and no forward declaration is necessary for a rule or for a destination policy.

**Comment by frankbu** [comment]
A few more questions.

1. Is source an optional field? If set, you get source-based policies, if missing, it works like 0.1?
2. are labels also optional, so that you can define a policy for all clusters (like in 0.1)?
3. can namespace be the wildcard namespace, in which case it applies to all?
4. can we set a policy for external services (e.g., httpbin.org)?

**Comment by rshriram** [comment]
My proposal:

```yaml
metadata:
  name: relaxed-cb-policy
  namespace: some-namespace
spec:
  circuitBreakers:
    simpleCb:
       failureThreshold: 30s
       maxConnections: 1000
       maxConcurrentRequests: 1000
---
metadata:
  name: aggressive-cb-policy
  namespace: some-namespace
spec:
  circuitBreakers:
    simpleCb:
       maxConnections: 100
       maxConcurrentRequests: 500
       failureThreshold: 5s
---
```

and in route rule,

```yaml
## Specify default rule to pickup default policy
metadata:
  name: reviewsRouteRule
  namespace: some-namespace
spec:
  precedence: 1
  destination: reviews
  route:
    - destPolicy: relaxed-cb-policy ## if not present, will be ignored and defaults will be used.
       weight: 100
---
## Policy specific to a source, for same destination
metadata:
  name: reviewsRouteRule2
  namespace: some-namespace
spec:
  precedence: 2
  destination: reviews
  match:
    source:
      name: productpage
      namespace: some-namespace
  route:
    - destPolicy:  aggressive-cb-policy
       weight: 100
---
## Apply policy to specific destination service version
## Share policies across different route rules
metadata:
  name: ratingsRouteRule
  namespace: some-namespace
spec:
  precedence: 1
  destination: ratings ## Rule for different service
  route:
    - labels:
         env: prod
         region: us-east
       destPolicy: relaxed-cb-policy # Reusing policy across two rules
       weight: 80
    - labels:
         env: prod
         region: us-west
       destPolicy: another-policy # Does not exist, default used.
       weight: 20
---
```
