### ISSUE TITLE
EnvoyFilter API Value field to match YAML equivalent.

### ISSUE THREAD

**Issue by timlaroche** [istio/api#2187]
Hi,

We're using the `client-go` api to build an EnvoyFilter in code. I am unable to create an object that matches the YAML config that we have. Specifically, the `Value` field in EnvoyFilter_EnvoyConfigObjectPatch.

Consider the YAML
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: sleeper
spec:
  workloadSelector:
    labels:
      app: sleeper
  configPatches:
    - applyTo: BOOTSTRAP
      patch:
        operation: MERGE
        value:
          bootstrap_extensions:
            - name: envoy.bootstrap.wasm
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.wasm.v3.WasmService
                singleton: true
                config:
                  name: manager
                  root_id: manager
                  vm_config:
                    vm_id: "manager"
                    runtime: "envoy.wasm.runtime.v8"
                    code:
                      remote:
                        http_uri:
                          uri: "http://wasmserver.bar/binary"
                          cluster: "outbound|80||wasmserver.bar.svc.cluster.local"
                          timeout: "10s"
                        sha256: "3d9f1dd3aee0fb485254af154694f1dc44919a8ae437e78979bce6af02e8ebf5"
                        retry_policy:
                          num_retries: 999999
```

I couldn't find any reference to anything inside the Istio API repo or Istio regarding vm_config etc. I also get a protobuf error if I convert the yaml underneath `value` to JSON and then unmarshal it into the value field. How would this translate to 
```go
v1alpha3.EnvoyFilter_EnvoyConfigObjectPatch{
		ApplyTo: v1alpha3.EnvoyFilter_EXTENSION_CONFIG,
		Patch: &v1alpha3.EnvoyFilter_Patch{
			Operation: v1alpha3.EnvoyFilter_Patch_ADD,
			Value:    whatGoesHere,
		}
```
Is this even possible at the moment?

Thanks
