### ISSUE TITLE
ExternalProcessor envoy filter fails validation in version 1.12.1, still validates v3alpha rather than v3

### ISSUE THREAD

**Issue by pedromarceOAT** [istio/api#2191]
**Bug description**
When trying to apply a configuration in version 1.12.1 with a type:

`http://type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor`

we receive an error:

`admission webhook "validation.istio.io" denied the request: configuration is invalid: Envoy filter: could not resolve Any message type: type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor
`
If we change the type to:

`type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3alpha.ExternalProcessor`

then validation is passed but execution of the filter fails with message: 

`{"level":"warning","time":"2021-12-17T14:29:39.609531Z","scope":"envoy config","msg":"gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) virtualInbound: Unable to unpack as envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor: type_url: \"type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3alpha.ExternalProcessor\"\nvalue: \"\\n\\016\\n\\014\\n\\nem-sidecar\\032\\010\\010\\001\\020\\001(\\0020\\002:\\002\\010\\001\"\n\n"}`

**Affected product area (please put an X in all that apply)**

[*] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ *] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Expected behavior**

We can use ExternalProcessor filter as per documentation.

**Steps to reproduce the bug**

Try to configure and use this envoy filter: https://www.envoyproxy.io/docs/envoy/v1.20.1/api-v3/extensions/filters/http/ext_proc/v3/ext_proc.proto#envoy-v3-api-msg-extensions-filters-http-ext-proc-v3-externalprocessor

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```
istioctl version --remote         
client version: 1.12.0
           control plane version: 1.12.1
                          data plane version: 1.12.1 (114 proxies), 1.10.3 (22 proxies)
```

```
kubectl version      
Client Version: version.Info{Major:“1”, Minor:“22", GitVersion:“v1.22.4”, GitCommit:“b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:“clean”, BuildDate:“2021-11-17T15:41:42Z”, GoVersion:“go1.16.10”, Compiler:“gc”, Platform:“darwin/arm64”}
                                    Server Version: version.Info{Major:“1", Minor:“21”, GitVersion:“v1.21.5-gke.1302", GitCommit:“639f3a74abf258418493e9b75f2f98a08da29733”, GitTreeState:“clean”, BuildDate:“2021-10-21T21:35:48Z”, GoVersion:“go1.16.7b7", Compiler:“gc”, Platform:“linux/amd64"}
```

**How was Istio installed?**

istio-operator

**Environment where bug was observed (cloud vendor, OS, etc)**

GCP -  GKE

FULL Configuration file:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: em-envoyfilter-annotate-http
  namespace: oat-em-dev
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
          portNumber: 8080
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.ext_proc
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor
            grpc_service:
              envoy_grpc:
                cluster_name: em-sidecar
            message_timeout: 1s
            processing_mode:
              request_header_mode: "SEND"
              response_header_mode: "SEND"
              request_body_mode: "NONE"
              response_body_mode: "NONE"
              request_trailer_mode: "SKIP"
              response_trailer_mode: "SKIP"
    - applyTo: CLUSTER
      match:
        context: ANY
      patch:
        operation: ADD
        value:
          connect_timeout: 0.25s
          http2_protocol_options: {}
          load_assignment:
            cluster_name: em-sidecar
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: 127.0.0.1
                          port_value: 18888
          name: em-sidecar
          type: STATIC
 
```

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
