### ISSUE TITLE
Indentation in example YAML in Istio destination rule reference page is incorrect

### ISSUE THREAD

**Issue by su225** [istio/api#2384]
https://istio.io/latest/docs/reference/config/networking/destination-rule/

In the below YAML, the indentation of `spec` is wrong. It should have been one level less.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: configure-client-mtls-dr-with-workloadselector
  spec:
    workloadSelector:
      matchLabels:
        app: ratings
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
        - port:
            number: 31443
          tls:
            credentialName: client-credential
            mode: MUTUAL
```
