### ISSUE TITLE
Add sidecar annotation for Ephemeral Storage

### ISSUE THREAD

**Issue by johndlong** [istio/api#2571]
**Describe the feature request**

Ephemeral Storage request/limit values are supported at the global level, but if the user defines a pod annotation for CPU and/or memory request/limits, then that global value is overridden and a user is no longer able to specify an ephemeral-storage request/limit.

**Describe alternatives you've considered**

We could potentially merge the global values into the conditional that annotation-based injection around the other `sidecar.istio.io/proxy*` annotations.  But that prevents any kind of per-Pod customization of resource consumption, and it makes a complicated user experience with the current `sidecar.istio.io/proxy*` annotations.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Additional context**

Ephemeral Storage requests/limits for a pod are scheduled/evicted based on the aggregate of all the container request/limits in that pod.  Therefore, if an application pod defines an `ephemeral-storage` resource request/limit and the sidecar does not, then the sidecar's ephemeral-storage consumption could potential result in eviction of the pod.

For more details about ephemeral storage:
https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#local-ephemeral-storage

**Comment by howardjohn** [comment]
does https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#customizing-injection work? this is more flexible than annotation

**Comment by johndlong** [comment]
> does https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#customizing-injection work? this is more flexible than annotation

Yeah, that also works.  Tested merging a CPU annotation w/ the customized injection and it looks like it works correctly:

```
template:
    metadata:
      annotations:
        sidecar.istio.io/proxyCPU: 500m
        sidecar.istio.io/proxyCPULimit: 1000m
    spec:
      containers:
... <app pod>
      - image: auto
        imagePullPolicy: Always
        name: istio-proxy
        resources:
          limits:
            ephemeral-storage: 20Mi
          requests:
            ephemeral-storage: 10Mi
```

end result appears correct:
```
    image: ...
    imagePullPolicy: Always
    name: istio-proxy
    ...
    resources:
      limits:
        cpu: "1"
        ephemeral-storage: 20Mi
      requests:
        cpu: 500m
        ephemeral-storage: 10Mi
```
