### ISSUE TITLE
DestinationRule containing only proxyPotocol is rejected by admission webhook

### ISSUE THREAD

**Issue by feynmanliang** [istio/api#3129]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

When I specify a `DestinationRule` containing just a `proxyProtocol` directive:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: foo
spec:
  host: foo.blueteam.svc.cluster.local
  trafficPolicy:
    proxyProtocol:
      version: "V1"
```

I encounter an admission webhook failure

```
DestinationRule/istio-system/mitmproxy dry-run failed: admission webhook "validation.istio.io" denied the request: configuration is invalid: traffic policy must have at least one field 
```

**Affected product area (please put an X in all that apply)**

[x] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Expected behavior**

I expect the destinationrule to be successfully created, because the `trafficPolicy` is nonempty.

**Steps to reproduce the bug**

Create `DestinationRule` given above

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

Istio 1.21.0
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2

**How was Istio installed?**

Helm

**Environment where bug was observed (cloud vendor, OS, etc)**

Oracle Kuberenetes Engine

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
