### ISSUE TITLE
Gateway selector not being parsed correctly

### ISSUE THREAD

**Issue by nmnellis** [istio/api#377]
I am seeing the following error in pilot after creating the below gateway config.
```
2018-02-17T02:46:37.724804Z	warn	LDS listing gateways: 1 error occurred:
 * YAML decoding error: selector:
- istio: gateway
servers:
- hosts:
  - example.com
  port:
    name: http
    number: 80
 json: cannot unmarshal array into Go value of type map[string]json.RawMessage
```

Gateway.yaml
```yaml
apiVersion: config.istio.io/v1alpha2
kind: Gateway
metadata:
  name: istio-ingress
  namespace: istio-system
spec:
  selector:
  - istio: gateway
  servers:
  - port:
      number: 80
      name: http
    hosts:
    - example.com

```
