### ISSUE TITLE
Change the service config to allow multiple adapters to be specified for a single aspect

### ISSUE THREAD

**Issue by ZackButcher** [istio/api#46]
Right now the [service config ties aspect configuration to a single adapter](https://github.com/istio/api/blob/master/mixer/v1/config/cfg.proto#L92). This means that to configure e.g. two metrics backends, I have to duplicate substantial configuration:

```
rules:
- selector: true
  aspects:
  - kind: metrics
    adapter: "statsd"
    params:
      metrics:
      - descriptor_: "request_count"
        value: "1"
        labels:
          source: "source.name"
          target: "target.name"
          service: "api.name"
          response_code: "response.code"
      - descriptor_:  "request_latency"
        value: "response.latency"
        labels:
          source: "source.name"
          target: "target.name"
          service: "api.name"
  - kind: metrics
    adapter: "prometheus"
    params:
      metrics:
      - descriptor_: "request_count"
        value: "1"
        labels:
          source: "source.name"
          target: "target.name"
          service: "api.name"
          response_code: "response.code"
      - descriptor_:  "request_latency"
        value: "response.latency"
        labels:
          source: "source.name"
          target: "target.name"
          service: "api.name"
```

We should change the `adapter` field to be a `repeated string` instead, so that aspect level configuration can be tied to multiple adapters:

```
rules:
- selector: true
  aspects:
  - kind: metrics
    adapters:
    - statsd
    - prometheus
    params:
      metrics:
      - descriptor_: "request_count"
        value: "1"
        labels:
          source: "source.name"
          target: "target.name"
          service: "api.name"
          response_code: "response.code"
      - descriptor_:  "request_latency"
        value: "response.latency"
        labels:
          source: "source.name"
          target: "target.name"
          service: "api.name"
```

Longer term, I think we should think about separating the configuration for which adapters are executed for a given aspect under a specific selector from the configuration of that aspect under that selector.
