### ISSUE TITLE
Explicit service to namespace mappings

### ISSUE THREAD

**Issue by rshriram** [istio/api#523]
Looking at the current RBAC support, no matter how much we try, the kubernetes namespace stuff (especially parsing the namespace from the DNS name) creeps into the core implementation making it unportable across platforms. The namespace to service mapping is implicit and the semantics get embedded into the code.

I propose that we create a separate CRD that explicitly defines the list of Istio namespaces and the set of services in each namespace. For simplicity, the lack of such a mapping in Kubernetes could indicate that the kube namespace is the Istio namespace, while in other platforms, all services fall into the default namespace.

The advantage of maintaining this explicit mapping are several:
1. Have services in different platforms be part of same namespace (some Kube and some CloudFoundry services under one namepsace called "foo")
2. When people wnat to bring custom DNS names in any platform, it becomes very easy to simply create a mapping that allows them to put them in the same istio namespace as existing kubernetes services, and thus take advantage of all the policy stuff we are doing.

Finally, most of our code gets decoupled from parsing namespace out of foo.ns.svc.cluster.local, and makes it very platform agnostic.

The CRD I am envisioning is something like this:

```yaml
type: config.istio.io/namespace
apiversion: v1
spec:
 MynamespaceFoo:
 - reviews.default.svc.cluster.local
 - mybookinfo.legacy.name.com
 - my-cloud-foundry.app.com
AnothernamespaceBar:
 - *.somedns.suffix
```

We can iterate on this mapping but this should go a long way towards making all our RBAC policies and other config stuff we are doing be platform independent. 

Thoughts? @louiscryan / @geeknoid / @smawson
