### ISSUE TITLE
 marshal the struct `HTTPMatchRequest` into YAML,got a `MatchType` under uri

### ISSUE THREAD

**Issue by dreadbird** [istio/api#570]
I use istio.io.api.networking.v1alpha3.VirtualService struct to create virtualservice resource.

I'm confused by the StringMatch.

When I want to use match,but I get the resource as flow:
why there is MacthType in the uri section?

```
spec:
  gateways:
  - demo-gateway
  hosts:
  - i-77env-gx77t.default.10.110.22.77.xip.io
  http:
  - match:
    - uri:
        MatchType:
          Prefix: /
    route:
    - destination:
        host: i-77env-gx77t-default-svcbxjlm
        subset: blue
```
