### ISSUE TITLE
The error:'Sum of weights in the weighted_cluster should add up to 100'  can not find which virtualservice is wrong

### ISSUE THREAD

**Issue by dreadbird** [istio/api#586]
When there is a virtualservice'destinationrule as flow 
```
 - match:
    - uri:
        prefix: /monthlyplan
    route:
    - destination:
        host: a.demo.svc.cluster.local
        subset: v1
    - destination:
        host: a.demo.svc.cluster.local
        subset: v2
      weight: 100
```
then I get error from ingressgateway pod logs:
```
[2018-07-18 00:48:44.664][148][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:218] gRPC config for type.googleapis.com/envoy.api.v2.Listener update rejected: Error adding/updating listener 0.0.0.0_443: Sum of weights in the weighted_cluster should add up to 100

[2018-07-18 00:48:44.664][148][warning][config] bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:70] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener 0.0.0.0_443: Sum of weights in the weighted_cluster should add up to 100
```

and then all the virtualservice is down,every hosts can not be use.

but,I do not kown whitch virtualservice is wrong by those error message
