### ISSUE TITLE
RFC: Container API objects

### ISSUE THREAD

**Issue by rshriram** [istio/api#651]
Decomposing APIs into smaller things (e.g., a separate resource for declaring subsets that decouples it from destination rules, or even the simple VirtualService and DestinationRule split) creates a lot of flexibility. At the same time, eventual consistency makes the implementation complex (atleast in networking) because if one or more pieces arrive late, the system (sidecars) could be in an inconsistent state (e.g., route points to versions, but the associated envoy clusters are not there because the destination rule has not arrived yet). We have been working around this issue by adding a slew of checks, behavioral assumptions/requirements on what the end user needs to do.

I propose that we create a new container API resource, one that can hold multiple types of APIs inside it. This provides us with the necessary collection object where all the related things are in one resource and can be applied without headaches.. At the same time, leaves the door open for flexibility, where people can use individual api objects to tweak stuff. 

 E.g.,

```yaml 
kind:NetworkingAPIContainer
spec:
 - type: virtualservice.networking.istio.io/v1alpha3
   spec:
      // virtual service spec
  - type: destinationrule.networking.istio.io/v1alpha3
     spec:
     // destination rule spec
```

The user can stuff any set of resources that need to be applied together. (we can tweak our docs as well). At the same time, users can also supply individual resources, as long as they understand the implications. 

I know that networking can benefit from something like this. Not sure if the same is true in Auth/RBAC/Mixer .. 

thoughts @geeknoid / @louiscryan ? or others (too many to name).
