### ISSUE TITLE
JSON Output is rejected by Pilot

### ISSUE THREAD

**Issue by michaelkipper** [istio/api#716]
Hi,

I'm trying to send an API call to Kubernetes, which is being rejected by Pilot.
The error message is:

```
admission webhook \"pilot.validation.istio.io\" denied the request: error decoding configuration: YAML decoding error:
gateways:
- irs-client-gateway
hosts:
- '*'
http:
- match:
  - uri:
      MatchType:
        Prefix: /
  route:
  - destination:
      host: irs-client
      port:
        Port:
          Number: 8080

unknown field \"MatchType\" in v1alpha3.StringMatch
```

I managed to reproduce this:

```go
package main

import (
	"encoding/json"

	"istio.io/api/networking/v1alpha3"
)

func main() {
	vs := v1alpha3.VirtualService{
		Http: []*v1alpha3.HTTPRoute{
			&v1alpha3.HTTPRoute{
				Match: []*v1alpha3.HTTPMatchRequest{
					&v1alpha3.HTTPMatchRequest{
						Uri: &v1alpha3.StringMatch{
							MatchType: &v1alpha3.StringMatch_Prefix{
								Prefix: "/",
							},
						},
					},
				},
			},
		},
	}

	buf, err := json.MarshalIndent(vs, "", "  ")
	if err != nil {
		panic("Could not marshal to JSON")
	}

	print(string(buf))
}
```

What I see is:

```shell
$ go run ./cmd/repro/main.go
{
  "http": [
    {
      "match": [
        {
          "uri": {
            "MatchType": {
              "Prefix": "/"
            }
          }
        }
      ]
    }
  ]
}
```

I'm not expecting to see `MatchType` in there, since the docs suggest this:

```yaml
 apiVersion: networking.istio.io/v1alpha3
 kind: VirtualService
 spec:
   hosts:
   - reviews.prod.svc.cluster.local
   http:
   - match:
     - uri:
         prefix: "/wpcatalog"
```

Is there a missing annotation in the Protobuf file, or am I using the type incorrectly?
