### ISSUE TITLE
Invalid Policy example in authentication/v1alpha1/policy.proto

### ISSUE THREAD

**Issue by esnible** [istio/api#851]
This is the example:

```
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: productpage_mTLS_disable
  namespace: frod
spec:
  targets:
  - name: productpage
```

`istioctl validate -f` reports 
```
* cluster-scoped authentication policy name must be "default", found "productpage_mTLS_disable"
* cluster-scoped authentication policy must not have targets
```

`kubectl apply` reports 
```
The Policy "productpage_mTLS_disable" is invalid: metadata.name: Invalid value: "productpage_mTLS_disable": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```
