### ISSUE TITLE
Unification of config API

### ISSUE THREAD

**Issue by kyessenov** [istio/api#94]
Some decisions from a meeting:
1. We do not need transactional semantics for the config updates, a regular key value store is sufficient for our purpose in Mixer and Manager
2. We may need to explore PATCH semantics for updates to allow long-lasting rollouts (since parent config might be concurrently updated).
3. Need to unify the key naming for config artifacts, in particular separate the query for mixer artifacts from the id of the artifact.

@andraxylia @mandarjog @ayj

**Comment by ayj** [comment]
Open items that require further discussion (please add/remove as necessary):

1. Versioning 
1. Validation
1. Consistency guarantees
1. Availability 
1. Performance

**Comment by kyessenov** [comment]
## Proposal to unify config documents and config keys

After discussion with @mandarjog @andraxylia @ayj , it seems we can start unification from the consistent conceptual model of the config, putting storage, perf, versioning, validation, and roll-outs aside. We have a common theme in Manager and Mixer that configuration consists of individual documents:
- route rules, destination policies, mesh config in Manager
- policy rules in Mixer, individual aspects in rules
- descriptors and adapter configuration in Mixer

The granularity of the document is dictated by two factors:
- External factor: the user should be able to deploy an individual configuration setting as a single operation. For example, for Mixer that means applying a blacklist with a selector is an operation and should not involve multiple steps such as listing all rules, appending an elements, and then submitting a new list.
- Internal factor: the boundary between selecting rules and selecting within rules should be conceptually simple. It seems that for Mixer rules that means that "selectors" belong to a configuration unit since it operates in the data plane; while "scope", "subject" and "ruleId" are used to find rules that need to be enforced, and are effectively selectors in the control plane. For Manager, "destination" field is the sole field for selecting rules and policies to apply.

Every configuration document should carry its metadata such as the "type" of the document, and a collection of "keys" that are used to select documents. All remaining fields compose the document content, as specified by the proto definitions:  that means selector/aspects are mixer rule content, routes/matches are proxy rule content. The configuration key has to be unique globally, and that is the only guaranteed constraint that is easy to enforce with a key-value storage. We should utilize consistent fields such as "type" and "name" for uniformity.

Applying these ideas to current config protos, I suggest we structure them as follows:
1. Route rule:
```yaml
# meta: note the lack of namespace
type: route-rule
destination: a.default.svc.cluster.local
name: favorite-rule
# content
precedence: 2
match: ...
route: ...
```
Sample REST: get `/config/route-rule/a.default.svc.cluster.local/favorite-rule`, list `/config/route-rule/a.default.svc.cluster.local`

2. Destination policy:
```yaml
# meta: note lack of namespace, name since only one policy per destination
type: destination-rule
destination: a.default.svc.cluster.local
# content
- tags:
     version: v1
  cirtcuitBreaker:...
```
Sample REST key: get `/config/destination-rule/a.default.svc.cluster.local`, list `/config/destination-rule/`

3. Mesh config:
```yaml
# meta: single object per installation
type: mesh-config
# content
...
``` 
Sample REST key:  get `/config/mesh-config`

4. Mixer rule:
```yaml
# meta
type: mixer-rule
scope: global
subject: a.default.svc.cluster.local
name: rate-limit
# content
selector: source.labels["app"]=="reviews" && source.labels["version"] == "v3"
aspects:
  - kind: quotas
    params:
      quotas:
      - descriptorName: RequestCount
        maxAmount: 5
        expiration: 1s
```
Sample REST key: get `/config/mixer-rule/global/a.default.svc.cluster.local/rate-limit`

5. Descriptor (need help from mixer folks)

**Comment by kyessenov** [comment]
@geeknoid @mandarjog @ayj @andraxylia

**Comment by mandarjog** [comment]
Mixer has the following additional types.
```
type: mixer-adapters   # note no subject
scope: global
name: rate-limit
```

```
type: mixer-descriptors   # note no subject
scope: global
name: rate-limit
```

**Comment by geeknoid** [comment]
​We're also going to need to define dictionaries within config...​

**Comment by kyessenov** [comment]
Can we get a worked out example of what is inside adapters and descriptors?

**Comment by mandarjog** [comment]
```yaml
type: mixer-aspects-version-rule   # note no subject
scope: global
subject: ns.svc.cluster.local
name: rate-limit
version-rule:
- version: v1
   weight: 50
- version: v2
   weight: 50
```

```yaml
type: mixer-adapters-version-rule   # note no subject
scope: global
name: rate-limit
version-rule:
- version: v1
   weight: 100
- version: v2
   weight: 0
```

**Comment by kyessenov** [comment]
These configs are enormous, let's think how to break apart adapters and descriptors.

**Comment by kyessenov** [comment]
what is this last post about?

**Comment by mandarjog** [comment]
Adapters are grouped on the 'impl' key
And descriptors have types. Descriptor types are already used as keys.

https://github.com/istio/api/blob/master/mixer/v1/config_api_swagger.yaml

Look at replaceAdapterConfig and replaceDescriptor

Using "iPhone 9";

**Comment by douglas-reid** [comment]
Re: naming

is the name for the descriptor:
- `/config/mixer-descriptor/global/quota/RequestCount` (or perhaps: `config/mixer/descriptor/global/quota/RequestCount`) or
- `RequestCount` or
- a completely different namespaced thing (like `istio.io/api/request_count`)
?

I feel like we want the resource names to be the first (and we should have that reflect in the documents themselves). At least, we should be consistent with: https://cloud.google.com/apis/design/resource_names

**Comment by kyessenov** [comment]
I'm not sure what the descriptor actually does. Is there significance to the name `RequestCount`, or it is just chosen for human-readability? The name has to include the scope since Mixer's overriding semantics is encapsulated to the scope/subject hierarchy.

**Comment by kyessenov** [comment]
@mandarjog please stop editing my examples :) I thought `quota` as a name is important since it's just a symbolic name to connect an aspect to an implementation. Why did you rename it to `quota-default`?

**Comment by douglas-reid** [comment]
@kyessenov my naming thought applies to more than just descriptors.

in a bunch of these examples, we could leave out the lines for `type`, `destination`,`scope`, `subject` and just have one `name` that is the relative resource name. 

So, `name: /v1/config/mixer/rules/global/a.default.svc.cluster.local/clueless-pet-rule` or `name: /v1/config/destinations/a.default.svc.cluster.local`.

**Comment by kyessenov** [comment]
True, but I think there is benefit to structured names. It's immediately clear what list operations do if you break the name into resource type, and primary key properties.

**Comment by mandarjog** [comment]
quota-default reflects the fact that there is a 1:n relationship between the adapter impl and the name of the configuration block.
It is also *not* the name of the aspect.

The impl is implicitly connected to the aspect because it registers itself as such.

That name is important because the aspect can use it to explicitly associate with the adapter.



Re: editing "your" example, looks like I wrote that comment originally. Edit it back if you need to, now that you know the reason.



Using "iPhone 9";

**Comment by kyessenov** [comment]
Ok, updating examples to reflect that there could be multiple adaptors for an aspect.

**Comment by kyessenov** [comment]
Regarding expicit/implicit declaration of the fact that `memQuota` satisfies `quota` aspect: I think either way is fine with statically-linked plugins. However, for a separate system than mixer, it would be nice to be able to query adaptors for an aspects without having to run mixer to get that information.

**Comment by ayj** [comment]
The association of rule (route/destination/mixer) to service (destination/scope/subject) is currently encoded in the rule itself. Does it make sense for this association to be distinct resource rather than combined with the rule/policy? 

An association would associate a service (or set of services via labels) to a set of rules based on service name, scope, etc. Associations could map one or more service to one or more rules. This composability might be easier to manage than creating N rules with identical content except for the subject.

This might also be useful for versioning and staged rollouts where rules could be considered immutable and only the association is updated (or new associations added), e.g. Association maps 5% of services to RulesV1 and 95% to RulesV2.

**Comment by kyessenov** [comment]
I think it's an interesting idea to think about an "association rule" (presumably not an individual binding of a rule to a service but some rule saying "match these ____ services to these ____ rules"). Mixer design uses config overrides that are scoped by authority. A cluster admin rule overrides a service produce rule, which is reflected by the fact that the higher authority "scope" rule is used for the same "subject". I'm not sure how to express that easily with more general associations.

**Comment by ayj** [comment]
Yes, service-to-rule binding could be N:N. Wouldn't authority belong with the binding with this model? It could either be an explicit field in the binding resource or perhaps the binding themselves are organized under hierarchical scope/authority.

**Comment by kyessenov** [comment]
Is the below example similar to what you have in mind:
```yaml
# meta
type: mixer-rule
name: clueless-pet-rule
# content
selector: source.labels["app"]=="reviews" && source.labels["version"] == "v3"
aspects:
  - kind: quota
    params:
      quota:
      - descriptorName: RequestCount
        maxAmount: 5
        expiration: 1s
```

```yaml
# meta
type: mixer-rule-binding
name: apply-to-default
# content
selector: service == "*.default.svc.cluster.local" && rule == clueless-pet-rule # select which service and rules to apply
authority: root # utmost authority, root decisions precedes decisions by lower authority
```
